### PR TITLE
Add scala 3 contributing guide - MVP

### PR DESCRIPTION
**Pull request by bishabosha**
this is the initial version of the Scala 3 contributing guide, optimised for dotty sprees.

### CODE REVIEW

**Review by anatoliykmetyuk — APPROVED** [review]

File: _overviews/scala3-contribution/arch-symbols.md [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+
+## Symbols
+`dotc/core/Symbols.scala`
+
+Symbols are references to definitions (e.g. of variables, fields, classes). Symbols can be used to refer to definitions for which we don't have ASTs (for example, from the Java standard library).
+
+`NoSymbol` is used to indicate the lack of a symbol.
+
+Symbols uniquely identify definitions, but they don't say what the definitions *mean*. To understand the meaning of a symbol
+we need to look at its *denotation* (spefically for symbols, a `SymDenotation`).
```
Comment (dwijnand) [inline _overviews/scala3-contribution/arch-symbols.md:72]:
```suggestion
we need to look at its *denotation* (specially for symbols, a `SymDenotation`).
```

Comment (anatoliykmetyuk) [reply _overviews/scala3-contribution/arch-symbols.md:72]: @sjrd @vincenzobaz could you apply this change while reviewing? @bishabosha won't do it since he's on vacation and I don't have access to @scalacenter branches.

File: _overviews/scala3-contribution/procedures-areas.md [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+
+Objects in the compiler that inherit from [Showable] can be pretty printed.
+The pretty-printing of objects is used in many places, from debug output,
+to user-facing error messages and printing of trees after each phase.
+
+Look in [RefinedPrinter] (or its parent class [PlainPrinter]) for the implementation of pretty printing.
+
+### Content of Error Messages
+
+You can find most error messages defined in [messages] (with IDs defined in [ErrorMessageID]). If the message
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-areas.md:23]:
```suggestion
You can find the definitions of most error messages in [messages] (with IDs defined in [ErrorMessageID]). If the message
```
?

File: _overviews/scala3-contribution/procedures-inspection.md [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+in the compiler, and produced artifacts.
+
+## Inspecting variables in-place
+
+Frequently we need to know what a particular variable's value is. Often, it is sufficient to use `println`.
+
+When printing a variable, it's always a good idea to call `show` on that variable: `println(x.show)`.
+Many objects of the compiler define `show`, returning a human-readable string.
+e.g. if called on a tree, the output will be the tree's representation as source code, rather than
+the raw data underlying.
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-inspection.md:20]:
```suggestion
the underlying raw data.
```

File: _overviews/scala3-contribution/procedures-inspection.md [hunk 4]
```diff
@@ -0,0 +1,186 @@
...
+|--------|-----------------------------------|
+|`i""`   | General purpose string formatting. It calls `.show` on objects <br/> mixing in Showable, `String.valueOf` otherwise |
+|`em""`  | Formatting for error messages: Like `i` but suppress <br/>follow-on, error messages after the first one if some <br/>of their arguments are "non-sensical". |
+|`ex""`  | Formatting with added explanations: Like `em`, but add <br/>explanations to give more info about type variables<br/>and to disambiguate where needed. |
+
+
+## Obtaining debug output from the compiler
+
+There are many compiler options that provide verbose debug output when compiling a file.
+You can find the full list in [ScalaSettings.scala] file. One particularly useful one
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-inspection.md:52]:
```suggestion
You can find the full list in the file [ScalaSettings.scala]. One particularly useful one
```

File: _overviews/scala3-contribution/procedures-inspection.md [hunk 5]
```diff
@@ -0,0 +1,186 @@
...
+all phases. As described in the [compiler lifecycle][3] each phase transforms the trees
+and types that represent your code in a certain way. This flag allows you to see exactly how.
+
+## Stopping the compiler early
+Sometimes you may want to stop the compiler after a certain phase, for example to prevent
+knock-on errors from occurring from a bug in an earlier phase. Use the flag
+`-Ystop-after:<phase-name>` to prevent any phases executing afterwards.
+
+> e.g. `-Xprint:<phase>` where `phase` is a miniphase, will print after
+> the whole phase group is complete, which may several miniphases after `phase`.
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-inspection.md:63]:
```suggestion
> the whole phase group is complete, which may be several miniphases after `phase`.
```

File: _overviews/scala3-contribution/procedures-inspection.md [hunk 6]
```diff
@@ -0,0 +1,186 @@
...
+Names:
+   0: ASTs
+   1: <empty>
+   2: Foo
+   3: <init>
+...
+```
+and so on.
+
+## Inspecting representation of types
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-inspection.md:99]:
```suggestion
## Inspecting the representation of types
```

File: _overviews/scala3-contribution/procedures-inspection.md [hunk 7]
```diff
@@ -0,0 +1,186 @@
...
+sbt:scala3> scala3-compiler/Test/runMain
+> dotty.tools.printTypes
+> "class Box { type X }"
+> "rhs"
+> "Box#X"
+[info] running (fork) dotty.tools.printTypes "class Box { type X }" rhs Box#X
+TypeRef(TypeRef(ThisType(TypeRef(NoPrefix,module class <empty>)),class Box),type X) [class dotty.tools.dotc.core.Types$CachedTypeRef]
+```
+
+Here are some other examples you can follow:
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-inspection.md:144]:
```suggestion
Here are some other examples you can try:
```

File: _overviews/scala3-contribution/procedures-inspection.md [hunk 8]
```diff
@@ -0,0 +1,186 @@
...
+- `...printTypes "" "class" "[T] extends Seq[T] {}"`
+- `...printTypes "" "method" "(x: Int): x.type"`
+- `...printTypes "" "type" "<: Int" "= [T] =>> List[T]"`
+
+### Don't just print: extracting further information
+
+`dotty.tools.printTypes` is useful to to at a glance see the representation
+of a type, but sometimes we want to extract more. We can instead use the
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-inspection.md:152]:
```suggestion
`dotty.tools.printTypes` is useful to see the representation
of a type at a glance, but sometimes we want to extract more. We can instead use the
```

File: _overviews/scala3-contribution/procedures-testing.md [hunk 9]
```diff
@@ -0,0 +1,201 @@
...
+type: section
+description: This page describes test procedures in the Scala 3 compiler.
+num: 10
+previous-page: procedures-efficiency
+next-page: procedures-checklist
+---
+
+It is important to add tests before a pull request, to verify that everythig is working as expected,
+and act as proof of what is valid/invalid Scala code (in case it is broken in the future).
+In this section we will see the testign procedures in Scala 3.
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-testing.md:12]:
```suggestion
In this section we will see the testing procedures in Scala 3.
```

File: _overviews/scala3-contribution/procedures-testing.md [hunk 10]
```diff
@@ -0,0 +1,201 @@
...
+Often however it is not necessary to test everything if your changes are localised to one area,
+we will see in the following sections the different kinds of tests, and how
+to run individual tests.
+
+## Compilation Tests
+
+Compilation tests run the compiler over input files, using various settings. Input files
+are found within the `tests/` directory at the root of the compiler repo.
+
+Test input files are categorised further by the virtue of placing them in the subdirectories
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-testing.md:32]:
```suggestion
Test input files are categorised further by placing them in the subdirectories
```

File: _overviews/scala3-contribution/procedures-testing.md [hunk 11]
```diff
@@ -0,0 +1,201 @@
...
+### Naming and Running a Test Case
+
+Tests are, by convention, named after the number of the issue they are fixing.
+e.g. if you are fixing issue 101, then the test should be named `i101.scala`, for a single-file test,
+or be within a directory called `i101/` for a multi-file test.
+
+To run the test, invoke the sbt command `testCompilation i101` (this will match all tests with `"i101"` in
+the name, so it is useful to use a unique name)
+
+The group tests – `pos`, `neg` etc – are defined in [CompilationTests]. If you want to run a group of tests, e.g.
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-testing.md:48]:
```suggestion
The test groups – `pos`, `neg`, etc. – are defined in [CompilationTests]. If you want to run a group of tests, e.g.
```

File: _overviews/scala3-contribution/procedures-testing.md [hunk 12]
```diff
@@ -0,0 +1,201 @@
...
+To achieve this, within `tests/pos/i101/`, add a suffix `_n` to each file name, where `n` is an integer defining the
+order in which the file will compile. E.g. if you have two files, `Lib.scala` and `Main.scala`, and you need them
+compiled separately – Lib first, Main second, then name them `Lib_1.scala` and `Main_2.scala`.
+
+**2: Without classpath dependency:** If your issue does not require a classpath dependency, your files can be compiled
+in a single run, this is called *joint compilation*. In this case use file names without the `_n` suffix.
+
+### Checking Program Output
+
+`tests/run` tests verify the runtime behaviour of a test case. The output is checked by invoking a main method
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-testing.md:76]:
```suggestion
`tests/run` tests verify the run-time behaviour of a test case. The output is checked by invoking a main method
```

File: _overviews/scala3-contribution/procedures-testing.md [hunk 13]
```diff
@@ -0,0 +1,201 @@
...
+```
+or
+```scala
+object Test extends scala.App:
+  assert(1 > 0)
+```
+
+If your program also prints output, this can be compared against `*.check` files.
+These contain the expected output of a program. Checkfiles are named after the issue they are checking,
+e.g. `tests/run/i101.check` will check both of `tests/run/i101.scala` and `tests/run/i101/`.
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-testing.md:89]:
```suggestion
e.g. `tests/run/i101.check` will check either `tests/run/i101.scala` or `tests/run/i101/`.
```

File: _overviews/scala3-contribution/procedures-testing.md [hunk 14]
```diff
@@ -0,0 +1,201 @@
...
+
+### Checking Compilation Errors
+
+`tests/neg` tests verify that a file does not compile, and user-facing errors are produced. There are other neg
+categories such as `neg-custom-args`, i.e. with `neg` prefixing the directory name. Test files in the `neg*`
+categories require annotations for the lines where errors are expected. To do this add one `// error` token to the
+end of a line for each error expected. e.g. if there are three errors expected, the end of line should contain
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-testing.md:96]:
```suggestion
end of a line for each expected error. For example, if there are three expected errors, the end of the line should contain
```

File: _overviews/scala3-contribution/procedures-testing.md [hunk 15]
```diff
@@ -0,0 +1,201 @@
...
+`// error // error // error`.
+
+You can verify the content of the error messages with a `*.check` file. These contain the expected output of the
+compiler. Checkfiles are named after the issue they are checking,
+e.g. `i101.check` will check both of `tests/neg/i101.scala` and `tests/neg/i101/`.
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-testing.md:101]:
```suggestion
e.g. `i101.check` will check either `tests/neg/i101.scala` or `tests/neg/i101/`.
```

File: _overviews/scala3-contribution/procedures-testing.md [hunk 16]
```diff
@@ -0,0 +1,201 @@
...
+*Note:* checkfiles are not required for the test to pass, however they do add more strong contraints that the errors
```
Comment (sjrd) [inline _overviews/scala3-contribution/procedures-testing.md:102]:
```suggestion
*Note:* checkfiles are not required for the test to pass, however they do add stronger constraints that the errors
```

**Review by sjrd — COMMENTED** [review]
Reviewed "Procedures" so far.

File: _overviews/scala3-contribution/arch-time.md [hunk 17]
```diff
@@ -0,0 +1,100 @@
...
+compilers change the type of a symbol destructively according to the "current
+phase". Another, more functional approach might be to have different symbols
+representing the same definition at different phases, which each symbol
+carrying a different immutable type. `dotc` employs yet another scheme, which
+is inspired by functional reactive programming (FRP): Symbols carry not a
+single type, but a function from compiler phase to type. So the type of a
+symbol is a time-indexed function, where time ranges over compiler phases.
+
+Typically, the definition of a symbol or other quantity remains stable for a
+number of phases. This leads us to the concept of a [period]. Conceptually,
```
Comment (sjrd) [inline _overviews/scala3-contribution/arch-time.md:47]: I'm surprised to see so much detail about `Period`, which I've never used/manipulated in practice. Conversely, I think it would be extremely valuable to have information about *time travel* with `atPhase`, which is used in many places in the codebase, and is currently missing.

File: _overviews/scala3-contribution/arch-symbols.md [hunk 18]
```diff
@@ -0,0 +1,133 @@
...
+data. But for the requirements of `dotc` it turns out that symbols are
+both too little and too much for this task.
+
+**Too little:** The attributes of a symbol depend on the phase. Examples:
+Types are gradually simplified by several phases. Owners are changed
+in phases `LambdaLift` (when methods are lifted out to an enclosing
+class) and Flatten (when all classes are moved to top level). Names
+are changed when private members need to be accessed from outside
+their class (for instance from a nested class or a class implementing
+a trait). So a functional compiler, a `Symbol` by itself met mean
```
Comment (sjrd) [inline _overviews/scala3-contribution/arch-symbols.md:34]: ?

File: _overviews/scala3-contribution/arch-symbols.md [hunk 19]
```diff
@@ -0,0 +1,133 @@
...
+much. Instead we are more interested in the attributes of a symbol at
+a given phase.
+
+**Too much:** If a symbol is used to refer to a definition in another
+compilation unit, we get problems for incremental recompilation. The
+unit containing the symbol might be changed and recompiled, which
+might mean that the definition referred to by the symbol is deleted or
+changed. This leads to the problem of stale symbols that refer to
+definitions that no longer exist in this form. Scala 2 compiler tried to
```
Comment (sjrd) [inline _overviews/scala3-contribution/arch-symbols.md:43]:
```suggestion
definitions that no longer exist in this form. The Scala 2 compiler tried to
```

File: _overviews/scala3-contribution/arch-symbols.md [hunk 20]
```diff
@@ -0,0 +1,133 @@
...
+address this problem by _rebinding_ symbols appearing in certain cross
+module references, but it turned out to be too difficult to do this
+reliably for all kinds of references. Scala 3 compiler attacks the problem at
```
Comment (sjrd) [inline _overviews/scala3-contribution/arch-symbols.md:46]:
```suggestion
reliably for all kinds of references. The Scala 3 compiler attacks the problem at
```

File: _overviews/scala3-contribution/arch-symbols.md (hunk 1 above)
Comment (sjrd) [reply _overviews/scala3-contribution/arch-symbols.md:72]: Shouldn't it be "specifically" instead?

File: _overviews/scala3-contribution/arch-symbols.md [hunk 21]
```diff
@@ -0,0 +1,133 @@
...
+`NoSymbol` is used to indicate the lack of a symbol.
+
+Symbols uniquely identify definitions, but they don't say what the definitions *mean*. To understand the meaning of a symbol
+we need to look at its *denotation* (spefically for symbols, a `SymDenotation`).
+
+Symbols can not only represent terms, but also types (hence the `isTerm`/`isType` methods in the `Symbol` class).
+
+## ClassSymbol
+
+`ClassSymbol` represents either a `class`, or an `trait`, or an `object`. For example, an object
```
Comment (sjrd) [inline _overviews/scala3-contribution/arch-symbols.md:78]:
```suggestion
`ClassSymbol` represents either a `class`, or a `trait`, or an `object`. For example, an object
```

File: _overviews/scala3-contribution/arch-symbols.md [hunk 22]
```diff
@@ -0,0 +1,133 @@
...
+  * a set of flags that contain semantic information about the definition (e.g. whether it's a trait or mutable). Flags are defined in `Flags.scala`.
+  * the type of the definition (through the `info` method)
+
+## Denotation
+[Comment with a few details:][Denotations2]
+
+A `Denotation` is the result of a name lookup during a given period
+
+* Most properties of symbols are now in the denotation (name, type, owner,
+  etc.)
```
Comment (sjrd) [inline _overviews/scala3-contribution/arch-symbols.md:113]: "are now": compared to when? This sentence doesn't seem to make sense to me.

File: _overviews/scala3-contribution/arch-context.md [hunk 23]
```diff
@@ -0,0 +1,43 @@
...
+  * `mode` (type checking mode)
+  * `typerState` (for example undetermined type variables)
+  * ...
+
+### Contexts in the typer
+The type checker passes contexts through all methods and adapts fields where
+necessary, e.g.
+
+```scala
+case tree: untpd.Block => typedBlock(desugar.block(tree), pt)(ctx.fresh.withNewScope)
```
Comment (sjrd) [inline _overviews/scala3-contribution/arch-context.md:30]: I don't understand how this line is an example for the sentence above.

File: _overviews/scala3-contribution/arch-context.md [hunk 24]
```diff
@@ -0,0 +1,43 @@
...
+```
+
+A number of fields in the context are typer-specific (`mode`, `typerState`).
```
Comment (sjrd) [inline _overviews/scala3-contribution/arch-context.md:33]: What does it mean to be "typer-specific"?

**Review by sjrd — COMMENTED** [review]
And that's the review for the Architecture.

File: _overviews/scala3-contribution/arch-symbols.md (hunk 1 above)
Comment (SethTisue) [reply _overviews/scala3-contribution/arch-symbols.md:72]: "for symbols specifically" would be the clearest and most idiomatic, IMO

File: _overviews/scala3-contribution/arch-symbols.md (hunk 18 above)
Comment (bishabosha) [reply _overviews/scala3-contribution/arch-symbols.md:34]: this entire page was just copy pasted from the old dotty website, so I added the banner to say it is a work in progress at the top of the page

Comment (bishabosha) [reply _overviews/scala3-contribution/arch-symbols.md:34]: same with the pages about contexts and periods

File: _overviews/scala3-contribution/arch-context.md (hunk 23 above)
Comment (bishabosha) [reply _overviews/scala3-contribution/arch-context.md:30]: this page was copied from the dotty website without much review, so I added a "work in progress" banner to the top

File: _overviews/scala3-contribution/arch-context.md (hunk 24 above)
Comment (bishabosha) [reply _overviews/scala3-contribution/arch-context.md:33]: I'm not sure, this page was just copied from dotty website

File: _overviews/scala3-contribution/arch-time.md (hunk 17 above)
Comment (dwijnand) [reply _overviews/scala3-contribution/arch-time.md:47]: I benefitted from this info, seeing as it's new in dotc.  But I don't disagree that phase travelling is even more important and I've never seen a good description of it.

Comment (bishabosha) [reply _overviews/scala3-contribution/arch-time.md:47]: This was copy-pasted from the original dotty website, but this would be good to add

File: _overviews/scala3-contribution/procedures-reproduce.md [hunk 25]
```diff
@@ -0,0 +1,130 @@
...
+to the first argument passed after the issue name. The command invoked would look like
+`issue foo original` to compile `original.scala`, and `issue foo alt` for `alt.scala`.
+
+In general, you can refer to arguments passed to the `issue <issue_name>` command using
+the dollar notation: `$1` for the first argument, `$2` for the second and so on.
+
+### Multiline Commands
+
+`launch.iss` files support putting commands accross multiple lines, which is useful for
+toggling lines by using a comment.
```
[the remark this answers is not in the document]
Comment (vincenzobaz) [reply _overviews/scala3-contribution/procedures-reproduce.md:96]: commands can span multiple lines. So it is easy to comment lines out to experiment with different options/arguments

**Review by vincenzobaz — APPROVED** [review]
The other reviewers probably have a lot more knowledge than me on this topic.
I wish I had this before my first spree!

I left some minor comments, but the guide looks very good and it contains a lot cool tips on testing. For the Spree I suggest to create a resume or shorter version, because there is a lot of material!

**Comment by anatoliykmetyuk** [comment]
Thanks everyone for the review and suggestions! I've applied the most straightforward ones while leaving more in-depth one for later. This is because we have only a couple days left until the spree, so we need to have something soon. Let's return to this PR in the future iterations of the development of this guide.
